id: ID5149747
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T23:15:43.789320'
last_modified: '2022-05-30T23:15:43.789334'
parser: null
source_metadata:
  title: Situ Paṇchen Series
  language: en
  description: 'Works by and about the influential scholar, grammarian and artist
    Situ Paṇchen Chökyi Jungne (si tu paṇ chen chos kyi ''byung gnas, 1700–1774):'
  volume:
    f9AD6:
      title: Pointing Out Instruction
      base_file: f9AD6.txt
      order: 1
      parent: Advice
    f6866:
      title: Instructions on the Fivefold Mahāmudrā
      base_file: f6866.txt
      order: 2
      parent: Mahāmudrā
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
